# Generated by Django 5.0.4 on 2024-06-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id_guru', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alamat', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id_mata_pelajaran', models.AutoField(primary_key=True, serialize=False)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('hari', models.CharField(max_length=20)),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('materi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id_ruangan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ruangan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.guru')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.matapelajaran')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.ruangan')),
            ],
        ),
    ]
